### ISSUE TITLE
h5daos_test_metadata_parallel crash while using Async I/O flag

### ISSUE THREAD

**Issue by berserk-fury** [HDFGroup/vol-daos#14]
Hi,

I am testing the `h5daos_test_metadata_parallel` test. When I ran it without using any flag it works. However, when I use the `-U` flag to use Async I/O it crashes.

**Seen in:**
DAOS commit b413447e
vol-daos v1.1.0rc2
and vol-daos commit 9ae044c

**Reproduction steps**

```
$ dmg  pool create --size 8G
Creating DAOS pool with automatic storage allocation: 8.0 GB NVMe + 6.00% SCM
Pool created with 100.00% SCM/NVMe ratio
-----------------------------------------
  UUID          : 6d9e2196-dcfe-4b78-82a9-8621a7ec87dd
  Service Ranks : 0
  Storage Ranks : 0
  Total Size    : 8.0 GB
  SCM           : 8.0 GB (8.0 GB / rank)
  NVMe          : 0 B (0 B / rank)

$ export D_LOG_FILE=/tmp/daos_client.log
$ export D_LOG_MASK=INFO
$ export DAOS_POOL=6d9e2196-dcfe-4b78-82a9-8621a7ec87dd
$ export HDF5_VOL_CONNECTOR=daos
$ export HDF5_PLUGIN_PATH=/usr/lib64/mpich/lib
$ export H5_DAOS_BYPASS_DUNS=TRUE

$ mpirun --hostfile ./hostfile -np 3 /home/eduardoj/repos/vol-daos/build/bin/h5daos_test_metadata_parallel -U
```
Here is the output of the command:

[output_h5daos_test_metadata_parallel_U.txt](https://github.com/HDFGroup/vol-daos/files/6092535/output_h5daos_test_metadata_parallel_U.txt)

**Comment by raylu-hdf** [comment]
-U option only works with -u option.  -u means unique group per rank where objects will be located under.    It uses independent metadata I/O with DAOS-VOL as the backend.

**Comment by raylu-hdf** [comment]
Options | Explanations | Default Values
-- | -- | --
-h | Help page |  
-a | Indicates to run collective metadata I/O using H5MPIIO as   the backend. -u   should not be used at the same time. |  
-A | Run the test for attribute object only |  
-b | The number of branches per tree node | 3
-c | The 2-D dimensions of the chunk size for datasets | 16x16
-d | The 2-D dimensions of the datasets | 16x16
-D | Run the test for dataset object only. |  
-e | The number of entries for the maps | 16
-f | The single dimension of the attributes | 16
-F | Run the test for file operations only |  
-g | The datatype of the datasets (char, int, llong, float,   double).  ‘llong’ stands for ‘long   long’. | int
-G | Run the test for group object only.  It also includes the test for link and   object copy. |  
-i | The number of trees (iterations) | 4
-I | The number of objects (groups, datasets, attributes, named   datatypes, and maps) | 1000
-j | The number of subgroups in the group objects | 16
-k | Enable the creation order tracking for the parent group   where all objects are under |  
-l | The layout of the datasets (contiguous, chunked, or   compact) | chunked
-m | The datatype of map object (int or vl).  ‘int’ means both the key and value are   integer type.  ‘vl’ means the key is   variable-length string while the value is variable-length integer. | int
-M | Run the test for map object only |  
-n | The number of iterations for file operations | 16
-o | Output file name (add the prefix “daos:” for H5MPIIO) | h5daos_test_mdata
-O | Run the test for object only (e.g. H5Ocopy) |  
-r | No write or read to the datasets |  
-s | No entry for maps |  
-t | No member in groups |  
-T | Run the test for named datatype only |  
-u | Unique group per task where objects will be located   under.  It uses independent metadata   I/O with H5VOL as the backend.  It   should not be used with -a. |  
-U | Use Async I/O, otherwise use sync I/O if not specified.  It should be used with -u only, not with -a. |  
-z | The number of levels (depths) for the tree | 0 (tree root only)

**Comment by berserk-fury** [comment]
Thank you for the information. I was able to run the test. I created [PR-15](https://github.com/HDFGroup/vol-daos/pull/15) to prevent others of making the same mistake.

**Comment by raylu-hdf** [comment]
You're welcome.
